### ISSUE TITLE
New Maintainer requested

### ISSUE THREAD

**Issue by gwern** [TerenceNg03/mueval#24]
I am no longer heavily involved in Haskell programming or using mueval for anything, so I would like to turn over maintainership of mueval to someone more active & responsible. Chris Done, unfortunately, is also unable to take it over.

The primary responsibility of a new maintainer would be packaging. (I never got into Stack, and I run a fairly old GHC+Cabal userland to avoid breaking my website, so while it works on my system, I dunno where else.) I'm otherwise not aware of any major issues with its current functionality but it'd probably be good to double-check the test suite and issues.

**Comment by gwern** [comment]
[/u/StdAds](https://www.reddit.com/user/StdAds) has [expressed interest](https://www.reddit.com/r/haskell/comments/14vx2rk/i_am_looking_for_a_new_maintainer_for_mueval/jrfetmu/). Anyone else?

**Comment by TerenceNg03** [comment]
I have taken over the maintianership and been working on this project. Issue closed.

**Comment by ncfavier** [comment]
The maintainership transfer does not look complete to me, as the [maintainer list for mueval on Hackage](https://hackage.haskell.org/package/mueval/maintainers/) does not show the new maintainer. The version published on Hackage is now lagging behind this repository, and maintainer access is required to publish a new version.

@TerenceNg03, do you have a Hackage account? If not, you would need to register one using [this page](https://hackage.haskell.org/users/register-request), then email the Hackage trustees to be added to the uploader group (this can take a while). Then, @gwern would have to add your Hackage handle to the mueval maintainers ([here](https://hackage.haskell.org/package/mueval/maintainers/edit)), so that you can upload the new version's tarball (generated using `cabal sdist`).

If this is too much of a hassle, I also volunteer to be a maintainer for this package. I am already a [maintainer](https://hackage.haskell.org/user/ncfavier) for most of the ecosystem that [lambdabot](https://github.com/lambdabot/lambdabot/) depends on.

**Comment by gwern** [comment]
> If this is too much of a hassle, I also volunteer to be a maintainer for this package. I am already a [maintainer](https://hackage.haskell.org/user/ncfavier) for most of the ecosystem that [lambdabot](https://github.com/lambdabot/lambdabot/) depends on.

I've added `ncfavier` to the Hackage mueval maintainer list. TerenceNg03, let me know your Hackage username.

**Comment by TerenceNg03** [comment]
Thanks for the information! I just created my account with username `Terence Ng` and is emailing to trustees. I would send an update here once this process is completed.

**Comment by TerenceNg03** [comment]
I have updated the pvp bounds and uploaded v0.9.4 to Hackage. This is the first time I uploaded a package to it. Thanks for everyone's help, and please do tell me if there is something I am missing.

**Comment by m4lvin** [comment]
Nice to see this is maintained! For future releases, could you also tag them on github so that one can see which commit corresponds to which hackage version?
